### ISSUE TITLE
v259 changed some things which broke some things :)

### ISSUE THREAD

**Issue by Letoric** [Qowyn/ark-tools#12]
java.lang.UnsupportedOperationException: Found unknown Version 7
java.lang.UnsupportedOperationException: Found unknown Version 7        at qowyn.ark.ArkSavegame.readBinaryHeader(ArkSav
egame.java:167)

        at qowyn.ark.ArkSavegame.readBinaryHeader(ArkSavegame.java:167) at qowyn.ark.ArkSavegame.readBinary(ArkSavegame.
java:138)

        at qowyn.ark.ArkSavegame.readBinary(ArkSavegame.java:138)       at qowyn.ark.ArkSavegame.<init>(ArkSavegame.java
:88)

        at qowyn.ark.ArkSavegame.<init>(ArkSavegame.java:88)    at qowyn.ark.tools.CreatureListCommands.listImpl(Creatur
eListCommands.java:109)

        at qowyn.ark.tools.CreatureListCommands.listImpl(CreatureListCommands.java:109) at qowyn.ark.tools.CreatureListC
ommands.wild(CreatureListCommands.java:67)

        at qowyn.ark.tools.CreatureListCommands.tamed(CreatureListCommands.java:62)     at qowyn.ark.tools.App.main(App.
java:117)

        at qowyn.ark.tools.App.main(App.java:117)

**Comment by Qowyn** [comment]
0.5.3 is out which may fix this.
