### ISSUE TITLE
Version 8 unknown

### ISSUE THREAD

**Issue by Letoric** [Qowyn/ark-tools#21]
Hi Qowyn. Looks like the new release of Ark came with a new version of save files. Have fun sir! :)

If you need some sent, let me know.

**Comment by TyrelSackett** [comment]
same.  happy to send anything needed to help as well.

java.lang.UnsupportedOperationException: Found unknown Version 8
        at qowyn.ark.ArkSavegame.readBinaryHeader(ArkSavegame.java:178)
        at qowyn.ark.ArkSavegame.readBinary(ArkSavegame.java:140)
        at qowyn.ark.ArkSavegame.<init>(ArkSavegame.java:90)
        at qowyn.ark.tools.CreatureListCommands.listImpl(CreatureListCommands.java:109)
        at qowyn.ark.tools.CreatureListCommands.wild(CreatureListCommands.java:67)
        at qowyn.ark.tools.App.main(App.java:117)

**Comment by van-dell** [comment]
Same. I get @TyrelSackett's error when doing the wild command, for tamed it's 62 instead of 67:

java.lang.UnsupportedOperationException: Found unknown Version 8
at qowyn.ark.ArkSavegame.readBinaryHeader(ArkSavegame.java:178)
at qowyn.ark.ArkSavegame.readBinary(ArkSavegame.java:140)
at qowyn.ark.ArkSavegame.<init>(ArkSavegame.java:90)
at qowyn.ark.tools.CreatureListCommands.listImpl(CreatureListCommands.java:109)
at qowyn.ark.tools.CreatureListCommands.tamed(CreatureListCommands.java:62)
at qowyn.ark.tools.App.main(App.java:117)

**Comment by b13n3rd** [comment]
Apart from the fact, that ark-tools does not know how to handle version 8 there seems to be little to no problem parsing the version savegames. I changed the code so version 8 is treated like version 7 and until now, i could not discover any bugs / problem.

Until qowyn provides an official solution, i provide a hotfixed build: [https://ark.bienerd.de/pages/ark-tools-hotfix.html](https://ark.bienerd.de/pages/ark-tools-hotfix.html) and created a pull request, stating the changes [https://github.com/Qowyn/ark-savegame-toolkit/pull/4](https://github.com/Qowyn/ark-savegame-toolkit/pull/4).

I think we should continue to provide problems / bugs / differences to version 7 to support.

**Comment by SwissBorn2Frag** [comment]
@b13n3rd 
Your download is detected by Chrome as suspect.

**Comment by b13n3rd** [comment]
@SwissBorn2Frag thank you for pointing out. Of course, the file is clean. I guess, chrome flags the file because of ark-tools.exe & ark-tools.jar contents. A note and virustotal scan was added to my page.

**Comment by SwissBorn2Frag** [comment]
Thanks. Your fix works :)

**Comment by van-dell** [comment]
@b13n3rd Thanks - I'm hoping this recompile fixes Ragnarok coords as well, they are in the source after all - have been calculating those manually until the update broke the tool.

**Comment by TyrelSackett** [comment]
well now we have version 9. Thanks Wildcard!  @b13n3rd any way to fix for version 9??

**Comment by SwissBorn2Frag** [comment]
@b13n3rd 
Can you please fix it again? :) 
Can you maybe add something like if(version >= "8") to automatically fix it for further versions?

**Comment by Qowyn** [comment]
Should be completely fixed with the 0.6.0 release
