### ISSUE TITLE
Unknown Cloud Inventory Version 4

### ISSUE THREAD

**Issue by dahlskebank** [Qowyn/ark-tools#22]
When I try to run c2j _(cloudToJson - Converts cloud data to .json)_ it returns the error message below. I believe this is related to the other version changes that Wildcard has made to save files. While I'm sure this will be fixed when you do get around to it, thought I'd point it out anyway...
```
java.lang.UnsupportedOperationException: Unknown Cloud Inventory Version 4
        at qowyn.ark.ArkCloudInventory.readBinary(ArkCloudInventory.java:65)
        at qowyn.ark.ArkCloudInventory.<init>(ArkCloudInventory.java:53)
        at qowyn.ark.ArkCloudInventory.<init>(ArkCloudInventory.java:31)
        at qowyn.ark.tools.ConvertingCommands.cloudToJson(ConvertingCommands.java:188)
        at qowyn.ark.tools.App.main(App.java:117)
```

**Comment by Qowyn** [comment]
Thanks for reporting this, fixed with v0.6.0
