### ISSUE TITLE
Out of heap space 

### ISSUE THREAD

**Issue by rob-bb** [Qowyn/ark-tools#3]
Hi, here is the output.

`D:\at>ark-tools.exe tamed TheCenter.ark t.txt
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at qowyn.ark.properties.PropertyRegistry.readProperty(PropertyRegistry.j
ava:61)
        at qowyn.ark.GameObject.loadProperties(GameObject.java:336)
        at qowyn.ark.ArkSavegame.readBinaryObjectPropertiesImpl(ArkSavegame.java
:246)
        at qowyn.ark.ArkSavegame.lambda$readBinaryObjectProperties$4(ArkSavegame
.java:240)
        at qowyn.ark.ArkSavegame$$Lambda$16/9727497.accept(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:20
5)
        at java.util.stream.IntPipeline$9$1.accept(IntPipeline.java:344)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams
.java:110)
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)

        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.ja
va:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.j
ava:151)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateSequential(ForEac
hOps.java:189)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

        at java.util.stream.IntPipeline.forEach(IntPipeline.java:404)
        at qowyn.ark.ArkSavegame.readBinaryObjectProperties(ArkSavegame.java:240
)
        at qowyn.ark.ArkSavegame.readBinary(ArkSavegame.java:138)
        at qowyn.ark.ArkSavegame.<init>(ArkSavegame.java:69)
        at qowyn.ark.tools.AnimalListCommands.listImpl(AnimalListCommands.java:8
2)
        at qowyn.ark.tools.AnimalListCommands.tamed(AnimalListCommands.java:54)
        at qowyn.ark.tools.App$$Lambda$2/17290025.accept(Unknown Source)
        at qowyn.ark.tools.App.main(App.java:52)

D:\at>`

It might be a pc issue, running on my work pc, win7 32bit so will try it at home on a real pc tonight.

**Comment by Qowyn** [comment]
Just found a huge memory optimization possibility, meanwhile i recommend using 64-bit Java, -m flag might help too.

**Comment by Qowyn** [comment]
Forum posts indicate this has been resolved, so closing.
