### ISSUE TITLE
jm2 NullPointerExecption if s+ flex pipe/cables are on the map

### ISSUE THREAD

**Issue by thFrgttn** [Qowyn/ark-tools#38]
If you use the m2j command, edit the map and then use j2m on a map that has S+ flex pipes or flex cables the tool crashes with a NullPointerException. (Looks like they use a custom struct without names)

I haven't tested the flex pipes/cables added to standard Ark with the Homestead update, but I'd guess they have the same issue.

Removing any flex pipes/cables before you use the m2j command works.

Development of these tools has stopped so this is more of a announcement and work around to any one else who comes across this problem.

**Comment by AkitaAttribute** [comment]
You should fix your title to j2m.  But thanks.

**Comment by AkitaAttribute** [comment]
```
java.lang.NullPointerException
        at qowyn.ark.properties.PropertyBase.<init>(PropertyBase.java:36)
        at qowyn.ark.properties.PropertyUnknown.<init>(PropertyUnknown.java:23)
        at qowyn.ark.properties.PropertyRegistry.readJson(PropertyRegistry.java:68)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at qowyn.ark.structs.StructPropertyList.<init>(StructPropertyList.java:44)
        at qowyn.ark.structs.StructRegistry.readJson(StructRegistry.java:59)
        at qowyn.ark.arrays.ArkArrayStruct.<init>(ArkArrayStruct.java:65)
        at qowyn.ark.arrays.ArkArrayRegistry.readJson(ArkArrayRegistry.java:52)
        at qowyn.ark.properties.PropertyArray.<init>(PropertyArray.java:59)
        at qowyn.ark.properties.PropertyRegistry.readJson(PropertyRegistry.java:68)
        at qowyn.ark.GameObject.readJson(GameObject.java:207)
        at qowyn.ark.GameObject.<init>(GameObject.java:73)
        at qowyn.ark.ArkSavegame.readJsonObjects(ArkSavegame.java:747)
        at qowyn.ark.ArkSavegame.readJson(ArkSavegame.java:679)
        at qowyn.ark.tools.ConvertingCommands.fromJson(ConvertingCommands.java:121)
        at qowyn.ark.tools.ConvertingCommands.jsonToMap(ConvertingCommands.java:28)
        at qowyn.ark.tools.App.main(App.java:125)

```
