### ISSUE TITLE
NullPointerException when converting ragnarok.json to ragnarok.ark

### ISSUE THREAD

**Issue by TGCAmris** [Qowyn/ark-tools#41]
I got the following error messages:

A:\ARKServer\ARKTools\ark-tools>ark-tools j2m ragnarokOM.json ragnarokOM.ark
java.lang.NullPointerException
        at qowyn.ark.properties.PropertyBase.<init>(PropertyBase.java:36)
        at qowyn.ark.properties.PropertyUnknown.<init>(PropertyUnknown.java:23)
        at qowyn.ark.properties.PropertyRegistry.readJson(PropertyRegistry.java:68)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at qowyn.ark.structs.StructPropertyList.<init>(StructPropertyList.java:44)
        at qowyn.ark.structs.StructRegistry.readJson(StructRegistry.java:59)
        at qowyn.ark.arrays.ArkArrayStruct.<init>(ArkArrayStruct.java:65)
        at qowyn.ark.arrays.ArkArrayRegistry.readJson(ArkArrayRegistry.java:52)
        at qowyn.ark.properties.PropertyArray.<init>(PropertyArray.java:59)
        at qowyn.ark.properties.PropertyRegistry.readJson(PropertyRegistry.java:68)
        at qowyn.ark.GameObject.readJson(GameObject.java:207)
        at qowyn.ark.GameObject.<init>(GameObject.java:73)
        at qowyn.ark.ArkSavegame.readJsonObjects(ArkSavegame.java:747)
        at qowyn.ark.ArkSavegame.readJson(ArkSavegame.java:679)
        at qowyn.ark.tools.ConvertingCommands.fromJson(ConvertingCommands.java:121)
        at qowyn.ark.tools.ConvertingCommands.jsonToMap(ConvertingCommands.java:28)
        at qowyn.ark.tools.App.main(App.java:125)

I got these messages when trying to convert a ragnarok.json savegame with mods back to .ark. And I got the very same error message when I trying to convert a ragnarok.json savegame without any mods back to .ark. So the mods aren't the problem. I tried first with jre 1.8.0_251 and then with jdk 14.0.1. Very same error messages. So the java version isn't the problem either. 

Unfortunately I have near zero programming experience myself. Would someone maybe look into this and update the ark-tools? Please? :D

**Comment by zokradonh** [comment]
Maybe the same error like #38 
Do you have S+ flex pipes/cables on your map?

**Comment by TGCAmris** [comment]
No mods: no s+ items :D

As I posted above: The exact same error messages came up when I tried to convert a save game file without any mods.

**Comment by zokradonh** [comment]
Oh, you are right. 🤦
