### ISSUE TITLE
Hibernation state reading crash

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [Qowyn/ark-tools#47]
Since the latest patch, the tools no longer work. I have been using it for years to export data for display on a website. It appears as though the project is now abandoned. I hope that is not the case because this is a great tool for many uses. Below is the error you get no matter what you try to do.

`java.lang.UnsupportedOperationException`
`        at qowyn.ark.ArkSavegame.readBinaryHibernation(ArkSavegame.java:387)`
`        at qowyn.ark.ArkSavegame.readBinary(ArkSavegame.java:172)`
`        at qowyn.ark.FileFormatBase.readBinary(FileFormatBase.java:30)`
`        at qowyn.ark.ArkSavegame.<init>(ArkSavegame.java:87)`
`        at qowyn.ark.tools.EditingCommands.exportThing(EditingCommands.java:145)`
`        at qowyn.ark.tools.App.main(App.java:125)`

I have updated my JRE to the latest and no change, so I am assuming that this is a change to the save format.

**Comment by stolenvw** [comment]
I get the same error when trying to read wild dino info

**Comment by AkitaAttribute** [comment]
@The-Great-Sephiroth and @stolenvw, if you would like to get it sorta working, you can comment out the lines of code: 385 to 388.  I was able to create json using this.  If you really want, I can create a fork.

**Comment by comical-uk** [comment]
> @The-Great-Sephiroth and @stolenvw, if you would like to get it sorta working, you can comment out the lines of code: 385 to 388. I was able to create json using this. If you really want, I can create a fork.

Hi

thank you very much for doing this :)

I've attempted to package your fork to use ark-tools.exe (although Im am not very familiar with what I am doing so may be doing something wrong) but after mvn package it I get an 

Error: Could not find or load main class qowyn.ark.tools.App

can you spot what I am doing wrong please

thanks!

**Comment by AkitaAttribute** [comment]
> > @The-Great-Sephiroth and @stolenvw, if you would like to get it sorta working, you can comment out the lines of code: 385 to 388. I was able to create json using this. If you really want, I can create a fork.
> 
> Hi
> 
> thank you very much for doing this :)
> 
> I've attempted to package your fork to use ark-tools.exe (although Im am not very familiar with what I am doing so may be doing something wrong) but after mvn package it I get an
> 
> Error: Could not find or load main class qowyn.ark.tools.App
> 
> can you spot what I am doing wrong please
> 
> thanks!

Rather than make you struggle with downloading both of the projects, here is a packaged JAR that is working.

[Here is a direct link to it in Google Drive](https://drive.google.com/uc?export=download&id=1NSghHhPHd-gldDkCpAEHm8PX322lXx1X)

**Comment by AkitaAttribute** [comment]
The fork was updated if you are interested in the changes.

**Comment by comical-uk** [comment]
fantastic, thank you very much!

**Comment by comical-uk** [comment]
> The fork was updated if you are interested in the changes.

sorry to bother you again, Ive just had the below on trying to do a m2j

Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at qowyn.ark.ArkArchive.getString(ArkArchive.java:198)
        at qowyn.ark.properties.PropertyStr.<init>(PropertyStr.java:26)
        at qowyn.ark.properties.PropertyRegistry.readBinary(PropertyRegistry.java:62)
        at qowyn.ark.GameObject.loadProperties(GameObject.java:375)
        at qowyn.ark.ArkSavegame.readBinaryObjectPropertiesImpl(ArkSavegame.java:340)
        at qowyn.ark.ArkSavegame.lambda$readBinaryObjectProperties$5(ArkSavegame.java:326)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.IntPipeline$Head.forEach(Unknown Source)
        at qowyn.ark.ArkSavegame.readBinaryObjectProperties(ArkSavegame.java:326)
        at qowyn.ark.ArkSavegame.readBinary(ArkSavegame.java:169)
        at qowyn.ark.FileFormatBase.readBinary(FileFormatBase.java:31)
        at qowyn.ark.tools.ConvertingCommands.toJson(ConvertingCommands.java:89)
        at qowyn.ark.tools.ConvertingCommands.mapToJson(ConvertingCommands.java:24)
        at qowyn.ark.tools.App.main(App.java:125)
        
        does that mean anything to you?

**Comment by AkitaAttribute** [comment]
> 

@comical-uk yeah.  That was the issue I was fixing in the most recent change.  Can I ask you to install Java 8?  If not, I can modify it further.

**Comment by AkitaAttribute** [comment]
@comical-uk additionally, I just found that this exists yesterday while browsing Reddit: https://drive.google.com/file/d/1h1b9D1dkaGhUBTirywN0gFNZ32QjrTMU/view?usp=sharing

It's a full UI for this.  It was ported to C#.  I don't think you're gonna run into the same issue.

**Comment by comical-uk** [comment]
> @comical-uk additionally, I just found that this exists yesterday while browsing Reddit: https://drive.google.com/file/d/1h1b9D1dkaGhUBTirywN0gFNZ32QjrTMU/view?usp=sharing
> 
> It's a full UI for this. It was ported to C#. I don't think you're gonna run into the same issue.

thanks. I'm on Java 8u351

the ASV is a fantastic tool, I was just using the ark-tools to be able to convert it back into a .ark afterward for a few things

**Comment by bomerman234** [comment]
> > 
> 
> @comical-uk yeah. That was the issue I was fixing in the most recent change. Can I ask you to install Java 8? If not, I can modify it further.

How to fix issue, I am on java 8

**Comment by BigBroza** [comment]
> Rather than make you struggle with downloading both of the projects, here is a packaged JAR that is working.
> 
> [Here is a direct link to it in Google Drive](https://drive.google.com/uc?export=download&id=1NSghHhPHd-gldDkCpAEHm8PX322lXx1X)

didn't fix anything sadly, I'm getting even more errors with that one

**Comment by AkitaAttribute** [comment]
> > Rather than make you struggle with downloading both of the projects, here is a packaged JAR that is working.
> > [Here is a direct link to it in Google Drive](https://drive.google.com/uc?export=download&id=1NSghHhPHd-gldDkCpAEHm8PX322lXx1X)
> 
> didn't fix anything sadly, I'm getting even more errors with that one

![image](https://user-images.githubusercontent.com/74178046/201514008-ebd05142-899b-48a8-b265-b8da18b29a3f.png)

**Comment by AkitaAttribute** [comment]
> > > 
> > 
> > 
> > @comical-uk yeah. That was the issue I was fixing in the most recent change. Can I ask you to install Java 8? If not, I can modify it further.
> 
> How to fix issue, I am on java 8

![image](https://user-images.githubusercontent.com/74178046/201514018-1c3f0e36-9544-49e4-9104-8dff1e50e398.png)

**Comment by AkitaAttribute** [comment]
So, for anyone who wants to get this working again, I'm willing to put in some effort to help you with it.  Since it works for me, this will require some effort, and back and forth with someone who has a version that isn't working.

If you'd like to work with me to get it working, feel free to join my discord [LINK](https://discord.gg/SB3kr5uF9Z) and ping SATAN.  Or just write something to the degree of wanting to help, since I get push notifications on my phone for that server.

**Comment by AkitaAttribute** [comment]
[This Updated JAR](https://drive.google.com/file/d/1NSghHhPHd-gldDkCpAEHm8PX322lXx1X/view?usp=share_link) I used after downloading java 8 on a fresh Windows 10 virtual machine.  It should be working.  I did make a few changes regarding the errors seen above.  

![image](https://user-images.githubusercontent.com/74178046/201517146-db1fd080-7b19-4fab-abbb-914047712aa1.png)

**Comment by comical-uk** [comment]
> So, for anyone who wants to get this working again, I'm willing to put in some effort to help you with it. Since it works for me, this will require some effort, and back and forth with someone who has a version that isn't working.
> 
> If you'd like to work with me to get it working, feel free to join my discord [LINK](https://discord.gg/SB3kr5uF9Z) and ping SATAN. Or just write something to the degree of wanting to help, since I get push notifications on my phone for that server.

thank you very much for the kind offer

I'd gladly help test, I used to use it a lot both to convert from the map saves and then to convert back into the map saves

I'm going to be out for a few hours today though :)

**Comment by AkitaAttribute** [comment]
Just updated the JAR [Same Link](https://drive.google.com/file/d/1NSghHhPHd-gldDkCpAEHm8PX322lXx1X/view?usp=share_link).

It now works for j2m as well.  Same issues with m2j.  Just some outdated library getting confused because it's overloaded.  Some casting to fix it.

**Comment by AkitaAttribute** [comment]
![image](https://user-images.githubusercontent.com/74178046/201520835-e7b6cf08-9760-4065-b49d-3399e8087090.png)

**Comment by comical-uk** [comment]
hey, thats seem to work fine converting them from the files that i've tested

however if I take a map save, then m2j and then j2m (without changes) then I get an error starting the server

the server starts fine normally, but not on a (fresh) map thats been m2j'd and then j2m'd

![image](https://user-images.githubusercontent.com/27687921/201532514-93e6deb9-9441-4de6-a952-f8718dd43b5b.png)

**Comment by AkitaAttribute** [comment]
> hey, thats seem to work fine converting them from the files that i've tested
> 
> however if I take a map save, then m2j and then j2m (without changes) then I get an error starting the server
> 
> the server starts fine normally, but not on a (fresh) map thats been m2j'd and then j2m'd
> 
> ![image](https://user-images.githubusercontent.com/27687921/201532514-93e6deb9-9441-4de6-a952-f8718dd43b5b.png)

Can you open task manager while running the game?  Idk if the error message is bad, but it's indicating it's an out of memory error.

**Comment by BigBroza** [comment]
> Just updated the JAR [Same Link](https://drive.google.com/file/d/1NSghHhPHd-gldDkCpAEHm8PX322lXx1X/view?usp=share_link).
> 
> It now works for j2m as well. Same issues with m2j. Just some outdated library getting confused because it's overloaded. Some casting to fix it.

thanks for the effort, I could m2j with this fix but I noticed the json is much smaller than usual. upon looking into it, it appears all creatures out of render range are missing from the json

it still helped me recover some of the data I needed so I am grateful nonetheless, god bless

**Comment by comical-uk** [comment]
> > hey, thats seem to work fine converting them from the files that i've tested
> > however if I take a map save, then m2j and then j2m (without changes) then I get an error starting the server
> > the server starts fine normally, but not on a (fresh) map thats been m2j'd and then j2m'd
> > ![image](https://user-images.githubusercontent.com/27687921/201532514-93e6deb9-9441-4de6-a952-f8718dd43b5b.png)
> 
> Can you open task manager while running the game? Idk if the error message is bad, but it's indicating it's an out of memory error.

sorry missed this. it goes up to 7gb, then down to 3.5gb. plenty of memory left on the host when it crashes

thanks

**Comment by AkitaAttribute** [comment]
> > Just updated the JAR [Same Link](https://drive.google.com/file/d/1NSghHhPHd-gldDkCpAEHm8PX322lXx1X/view?usp=share_link).
> > It now works for j2m as well. Same issues with m2j. Just some outdated library getting confused because it's overloaded. Some casting to fix it.
> 
> thanks for the effort, I could m2j with this fix but I noticed the json is much smaller than usual. upon looking into it, it appears all creatures out of render range are missing from the json
> 
> it still helped me recover some of the data I needed so I am grateful nonetheless, god bless

Thanks for the reply.  I will look into it, but I'm no expert when it comes to byte analysis.  That's why not many people have done this, and Qowyn's stuff is still important.  

I've basically commented out an error saying there is an issue with the hibernated creatures being read to get anything to work at all.

So, for now, this is probably as good as I can get it.  I'll continue to poke at it now and then though.

**Comment by comical-uk** [comment]
no worries, thanks for your efforts!

**Comment by The-Great-Sephiroth** [comment]
I have not signed into Github in ages and just saw the notification for this. I deciphered a lot of the old Daggerfall BSA format back in the day (all binary formats) and can try to help, but it's been a decade or more since I did so.

**Comment by Alexander3a** [comment]
i have made a fork that fixes this completly and adds support for reading cryopot data


https://github.com/Qowyn/ark-tools/issues/47#issuecomment-1312846926
this is because it sets the hibernated objects to -1 and thats overflows so it tries to allocate a lot of memory for nothing that also explains the high file size

**Comment by AkitaAttribute** [comment]
@Alexander3a did you make the fork public?  Can you share a link?  I don't see it on your page or on the forks page of this repo.

> i have made a fork that fixes this completly and adds support for reading cryopot data

**Comment by Alexander3a** [comment]
@AkitaAttribute 
its not a "proper" fork since i basicly merged the ark-tools and toolkit into one project so i dont have to edit them seperatly
i may split it again to make a proper fork if there is enough interesst in the source but at the moment it seems pretty useless
i woud be happy to give out the compiled jar file if you need it

**Comment by AkitaAttribute** [comment]
@Alexander3a is it published on GH?  I can compile it myself, unless you would rather not make it public.

**Comment by Alexander3a** [comment]
@AkitaAttribute 
do your have a discord i coud add you or something?

**Comment by AkitaAttribute** [comment]
SATAN#4417

**Comment by sae220** [comment]
@Alexander3a 
Could you share the fork with me?
Discord ID: sae220

**Comment by The-Great-Sephiroth** [comment]
> @AkitaAttribute its not a "proper" fork since i basicly merged the ark-tools and toolkit into one project so i dont have to edit them seperatly i may split it again to make a proper fork if there is enough interesst in the source but at the moment it seems pretty useless i woud be happy to give out the compiled jar file if you need it

I would be interested in this. We've been stuck with our site since this stopped working last November. We used the tools to export data that was parsed via PHP into HTML for a private site for our server cluster. Any chance you're still willing to share the binary or the sources? I'm actually a C++ programmer but Java isn't that bad and I could likely do a C++ tool if I understood the file format.
