### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by comical-uk** [Qowyn/ark-tools#48]
Hi

I just got this error on a m2j

Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at qowyn.ark.ArkArchive.getString(ArkArchive.java:198)
        at qowyn.ark.properties.PropertyStr.<init>(PropertyStr.java:26)
        at qowyn.ark.properties.PropertyRegistry.readBinary(PropertyRegistry.java:62)
        at qowyn.ark.GameObject.loadProperties(GameObject.java:375)
        at qowyn.ark.ArkSavegame.readBinaryObjectPropertiesImpl(ArkSavegame.java:340)
        at qowyn.ark.ArkSavegame.lambda$readBinaryObjectProperties$5(ArkSavegame.java:326)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.IntPipeline$Head.forEach(Unknown Source)
        at qowyn.ark.ArkSavegame.readBinaryObjectProperties(ArkSavegame.java:326)
        at qowyn.ark.ArkSavegame.readBinary(ArkSavegame.java:169)
        at qowyn.ark.FileFormatBase.readBinary(FileFormatBase.java:31)
        at qowyn.ark.tools.ConvertingCommands.toJson(ConvertingCommands.java:89)
        at qowyn.ark.tools.ConvertingCommands.mapToJson(ConvertingCommands.java:24)
        at qowyn.ark.tools.App.main(App.java:125)

thanks

**Comment by bomerman234** [comment]
I am getting the same error, did you by any chance find out how to solve it?
