### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by DrunkMunki** [Qowyn/ark-tools#5]
i ran this command **ark-tools.exe tamed TheIsland.ark dinos** and got an out of memory error, i updated java and over wrote the files with the latest version

 
> Exception in thread "main" java.lang.OutOfMemoryError: Direct buffer memory
>         at java.nio.Bits.reserveMemory(Unknown Source)
>         at java.nio.DirectByteBuffer.<init>(Unknown Source)
>         at java.nio.ByteBuffer.allocateDirect(Unknown Source)
>         at qowyn.ark.ArkSavegame.<init>(ArkSavegame.java:68)
>         at qowyn.ark.tools.CreatureListCommands.listImpl(CreatureListCommands.java:109)
>         at qowyn.ark.tools.CreatureListCommands.tamed(CreatureListCommands.java:62)
>         at qowyn.ark.tools.App.main(App.java:114)

**Comment by DrunkMunki** [comment]
possible fix, but im not a coder so i dont know what to do: http://www.java67.com/2014/01/how-to-fix-javalangoufofmemoryerror-direct-byte-buffer-java.html

**Comment by DrunkMunki** [comment]
fixed issue by removing 32bit Java and installing 64bit and using the command:
`java -Xmx2G -jar ark-tools.jar tamed TheIsland.ark dinos`
