### ISSUE TITLE
Could not be used?

### ISSUE THREAD

**Issue by cokll** [Qowyn/ark-tools#6]
`[root@localhost ~]# java -jar ark-tools.jar players /root/Saved/TheIsland.ark /root/bak/     
java.lang.NullPointerException
        at org.glassfish.json.UnicodeDetectingInputStream.fillBuf(UnicodeDetectingInputStream.java:90)
        at org.glassfish.json.UnicodeDetectingInputStream.detectEncoding(UnicodeDetectingInputStream.java:129)
        at org.glassfish.json.UnicodeDetectingInputStream.<init>(UnicodeDetectingInputStream.java:76)
        at org.glassfish.json.JsonParserImpl.<init>(JsonParserImpl.java:76)
        at org.glassfish.json.JsonReaderImpl.<init>(JsonReaderImpl.java:68)
        at org.glassfish.json.JsonProviderImpl.createReader(JsonProviderImpl.java:131)
        at javax.json.Json.createReader(Json.java:220)
        at qowyn.ark.tools.CommonFunctions.readJson(CommonFunctions.java:110)
        at qowyn.ark.tools.CommonFunctions.readJsonRelative(CommonFunctions.java:123)
        at qowyn.ark.tools.DataManager.loadData(DataManager.java:33)
        at qowyn.ark.tools.PlayerListCommands.players(PlayerListCommands.java:81)
        at qowyn.ark.tools.App.main(App.java:114)`

Tribes no problem

**Comment by Qowyn** [comment]
The cause of this has been a missing ark_data.json file, the newest version will report this as "Unable to load data file ./ark_data.json"

**Comment by cokll** [comment]
How to get ark_data.json

**Comment by Qowyn** [comment]
Every release includes the current version (at the time of release) in the ark-tools.zip and ark-tools.7z files. The newest version (and translated versions) can be downloaded here: https://ark-tools.seen-von-ragan.de/data/

**Comment by cokll** [comment]
Thanks very much

**Comment by Gnurfos** [comment]
Hi, I think now that the json file is not in the release zips, you should improve the error message again, saying one needs to run updateData (not everyone reads the whole doc :))
